### PR TITLE
Infer rels based on heads and tails

### PR DESCRIPTION
**Pull request by baxtree**
This PR added inference on _relation_s between a known pair of _head_ and _tail_. Can anybody review the change? Thanks.

### CODE REVIEW

**Comment by louisccc** [comment]
looks fine, but only TransE has been changed accordingly.

**Comment by baxtree** [comment]
Hi, @louisccc, is TransE not the only model class providing inference methods currently?

**Comment by louisccc** [comment]
hi @baxtree yea.. for the unit tests we now only have tested TransE. I will be adding soon :)

**Comment by baxtree** [comment]
Oh cool! That will be really useful across all models. 👍

**Pull request merged**
