### PR TITLE
Add inference capabilities to conve, convkb, distmult, ntn, proje_pointwise, slm and sme

### PR DESCRIPTION
**Pull request by baxtree**
Following #87 , this PR has expanded inference on heads, tails and rels to conve, convkb, distmult, ntn, proje_pointwise, slm and sme models. It extracted default implementation on `distance()` and `infer_*s()` into `InferenceMeta` for the purpose of easy sharing and overriding. Thanks!

### CODE REVIEW

**Comment by xibai** [comment]
Also, separated out calculations on L1 norm and L2 norm into `dissimilarity()` used by `infer_*s()` and it keeps `distance()` clean for each model. Added `infer_*s()` to hole, complex, rotate and tucker. There will be extra work and care to be taken for inference with kg2e, rescal and transg so the implementation needs to be discussed and done on a separate PR.

**Comment by baxtree** [comment]
Also, separated out calculations on L1 norm and L2 norm into `dissimilarity()` used by `infer_*s()` and it keeps `distance()` clean for each model. Added `infer_*s()` to hole, complex, rotate and tucker. There will be extra work and care to be taken for inference with kg2e, rescal and transg so the implementation needs to be discussed and done on a separate PR.

**Comment by baxtree** [comment]
Hi, @louisccc. Is there anybody happy to have a review on this PR?

**Comment by louisccc** [comment]
Yes I can do !

**Comment by louisccc** [comment]
I will say its probably not a good idea to place the implementation in a metaclass (inferencemeta.py), maybe we should look for some other ways to refactor this. But its general good now.

**Comment by baxtree** [comment]
Agreed. The InferenceMeta could be refactored into a separate concrete class (e.g., inferer.py) and that would make KGMeta.py stay true abstract albeit being up to the overall code design. Cheers!

**Pull request merged**
