### PR TITLE
relax on tensorflow version

### PR DESCRIPTION
**Pull request by figroc**
According to `README.md`, multiple versions of tensorflow would be good in most cases. I've tested it against version r1.14.0 and r1.15.0 in my working scenario. Should we let the version be in range >=1.13.1,<2 ?

### CODE REVIEW

**Comment by louisccc** [comment]
sounds good.

**Comment by figroc** [comment]
> sounds good.

but closed without merge? 🤔

**Comment by figroc** [comment]
the status of this pr is weird. it seems closed without merged 🤔

**Comment by figroc** [comment]
the status of this pr is weird. it seems closed without merged 🤔

**Pull request merged**
